[ACT-482] Add calls to push step
bitrise-steplib/steps-cache-push pull request #43
Opened 2020-08-19 16:01 UTC by Szabadember

2020-08-25 18:25 UTC, Szabadember commented on main.go
> +			log.Debugf("Found a path exceeding 1 GB: %s", pth)
if a file exceeds 1GB, the path to the file and all parent folders will be included here. Is this the way this should work?

2020-08-27 13:04 UTC, godrei requested changes

2020-08-27 13:04 UTC, godrei commented on main.go
> +func dirSize(path string) (int64, error) {
unused function, please remove it

2020-08-27 13:16 UTC, godrei approved these changes

2020-08-27 13:36 UTC, merged